### ISSUE TITLE
Fazer o loop dos usuários, converter em array e exibir os dados na página

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/dojophp#16]
Desafio| Complexidade | Atribuido à |
|---| ---| ---|
Fazer o loop dos usuários, converter em array e exibir os dados na página | Médio | @MasirLink-Mtecnology |

Material de apoio:
 * [PHP Arrays Ex. #1: Simple Array](https://www.phpexercises.com/php-simple-array-exercise.html) (exercício)

O desafio é pegar na lista de pessoas no ficheiro `data/codingdojo.json`, tornar num array e de seguida fazer a apresentação da mesma informação numa página web(html).

**## Passos**
 * Faça o fork do repositório
 * Crie o seu branch onde irá trabalhar com o git
   Exemplo:  **`git checkout -b nome-da-branch`**
* Resolva o desafio e de seguida paça o push
  `git push --set-upstream nome-da-branch`

------------------
 **Nota**:  Mantenha o seu fork atualizado com as mudanças do repositório original

      git remote add upstream git@github.com:codingdojoangola/dojophp.git
      git checkout desafios
      git pull upstream desafios
      git pull origin desafios

**Comment by MasirLink-Mtecnology** [comment]
Cage o ficheiro onde encontro

**Comment by JoseCage** [comment]
> Cage o ficheiro onde encontro

O ficheiro está dentro `data` @MasirLink-Mtecnology

**Comment by e200** [comment]
. O Ficheiro??? Já Dei Uma Olhada Na Repo, Não Vejo.

**Comment by JoseCage** [comment]
> O Ficheiro??? Já Dei Uma Olhada Na Repo, Não Vejo.

1: Ler passo a passo do ticket
2: ver onde eu menciono que o ficheiro é gravado..
:bug: :bug: :bug: 

Aqui vai https://github.com/codingdojoangola/dojophp/blob/desafios/data/codingdojo.json

**Comment by JoseCage** [comment]
Só falta eu adicionar o restante do pessoal.. Mas o ficheiro existe....

**Comment by e200** [comment]
. Acredita Em Mim: o Arquivo JSON Não Existe [Nesse Link](https://github.com/masirlink-mtecnology).

**Comment by e200** [comment]
. Agora Sim Deste o Link Correcto.

**Comment by e200** [comment]
. Eu Já Revirei Os Dois Repositórios, Não Há Files Lá.

**Comment by JoseCage** [comment]
Vocês olharam no repositório por acaso?? 

É onde está o ficheiro que dizes " Agora Sim Deste o Link Correcto."...

**Comment by JoseCage** [comment]
Sem usar o link que te passei navegue até o diretório principal, na pasta *data*.. @e200

**Comment by JoseCage** [comment]
> Eu Já Revirei Os Dois Repositórios, Não Há Files Lá.

E o facto de ires em mais de 1 repositório indica que não entenderam ou procuraram sem prestar atenção..

O ficheiro está lá e existe..

**Comment by JoseCage** [comment]
Desafio resolvido..

**PullRequest** da resposta #26  

Resolvido por |Complexidade | Pontos |
|--- |---| ---|
| @acidiney    | Baixa |  20 |

Obrigado @acidiney    pela disponibilidade..

Já tem mais 20 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by JoseCage** [comment]
Desafio resolvido..

**PullRequest** da resposta #29  

Resolvido por |Complexidade | Pontos |
|--- |---| ---|
| @guimar86    | Baixa |  20 |

Obrigado @guimar86    pela disponibilidade..

Já tem mais 20 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by e200** [comment]
. O Quê Que Falta Para Fecharem Já Esse Exercício?

**Comment by JoseCage** [comment]
@e200 Não faz muita diferença.. Mas obrigado por lembrar..
