### ISSUE TITLE
Armazenar nome, e-mail e telefone (array) dentro de uma variável e imprimir na tela

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/dojophp#17]
Complexidade | Atribuido à |
| ---| ---|
Médio | @JoaoCasimiro, @jeronimo86  |

Material de apoio:
 * [Variáveis e Constantes no PHP](http://www.diogomatheus.com.br/blog/php/variaveis-e-constantes-no-php/) (post)

O desafio é criar uma variável contendo um array de nomes, email, e telefone de pelo menos 3 pessoas e de seguida retornar esses valores com a função `echo` do PHP.

**## Passos**
 * Faça o fork do repositório
 * Crie o seu branch onde irá trabalhar com o git
   Exemplo:  **`git checkout -b nome-da-branch`**
* Resolva o desafio e de seguida paça o push
  `git push origin nome-da-branch`

------------------
 **Nota**:  Mantenha o seu fork atualizado com as mudanças do repositório original

      git remote add upstream git@github.com:codingdojoangola/dojophp.git
      git checkout desafios
      git pull upstream desafios
      git pull origin desafios

**Comment by e200** [comment]
. Retornar Ou Exibir?

**Comment by e200** [comment]
. Ohw... Não Reparei Que Cada Exercício Tem Um Destinatário.

**Comment by JoseCage** [comment]
> Retornar Ou Exibir?

de alguma forma "**é exibido**" o que "**é retornado**". Em algum ponto estão relacionados, mas creio que para o caso o termo seria *exibir*.

**Comment by JoseCage** [comment]
Bom trabalho @acidiney.. Desafío resolvido..

**Comment by JoseCage** [comment]
Desafio resolvido..

**PullRequest** da resposta #25 

Resolvido por |Complexidade | Pontos |
|--- |---| ---|
| @acidiney  | Médio |  40 |

Obrigado @acidiney pela disponibilidade..

Já tem mais 40 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..
