### ISSUE TITLE
Pegar data atual e retornar o dia da semana

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/dojophp#18]
Complexidade | Atribuido à |
| ---| ---|
Baixa | @acidiney |

Material de apoio:
 * ()

O desafio aqui é criar uma função que verifica se a data atual é por exemplo *segunda-feira*, terça ou qualquer outro dia da semana..

**## Passos**
 * Faça o fork do repositório
 * Crie o seu branch onde irá trabalhar com o git
   Exemplo:  **`git checkout -b nome-da-branch`**
* Resolva o desafio e de seguida paça o push
  `git push origin nome-da-branch`

------------------
 **Nota**:  Mantenha o seu fork atualizado com as mudanças do repositório original

      git remote add upstream git@github.com:codingdojoangola/dojophp.git
      git checkout desafios
      git pull upstream desafios
      git pull origin desafios

**Comment by acidiney** [comment]
Esse desafio é lindo kk

**Comment by JoseCage** [comment]
> Esse desafio é lindo kk

hahah @acidiney bora codar mais essa rsrs..

**Comment by JoseCage** [comment]
Desafio resolvido..

**PullRequest** da resposta #23 

Para visualizar o exemplo de implementação acessar a app [dojophp](http://dojophp.herokuapp.com/DiaDaSemana/)

Resolvido por |Complexidade | Pontos |
|--- |---| ---|
| @acidiney  | Baixa |  20 |

Obrigado @acidiney  pela disponibilidade..

Já tem mais 20 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by JoseCage** [comment]
Desafio resolvido..

**PullRequest** da resposta #22 

Resolvido por |Complexidade | Pontos |
|--- |---| ---|
| @e200   | Baixa |  20 |

Obrigado @e200   pela disponibilidade..

Já tem mais 20 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by JoseCage** [comment]
Prontos... @acidiney e @e200 obrigado pela participação..
