### ISSUE TITLE
Calcular e exibir idade com base na data de nascimento

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/dojophp#2]
Desafio| Complexidade | Atribuido à |
|---| ---| ---|
Calcular a idade do usuário | Muito baixa | `#cda` |

Material de apoio:
 * [Manual PHP](http://php.net/manual/en/function.date.php) (tópico: date)
 * [Trabalhando com datas no PHP](http://blog.thiagobelem.net/trabalhando-com-datas-no-php) (post)

Com este desafio a intenção é começar com aquilo que é um requisito básico para quem deseja trabalhar com *PHP* (aplica-se a outras linguagens) que é trabalhar com cálculos e data.

**## Passos**
 * Faça o fork do repositório
 * Crie o seu branch onde irá trabalhar com o git
   Exemplo:  **`git checkout -b calcudadora-de-idade`**
* Resolva o desafio e de seguida faça o push
  `git push --set-upstream calcudadora-de-idade`

------------------
 **Nota**:  Mantenha o seu fork atualizado com as mudanças do repositório original

      git remote add upstream git@github.com:codingdojoangola/dojophp.git
      git checkout desafios
      git pull upstream desafios

**Comment by JoseCage** [comment]
@jeronimo86 caso esteja encarando alguma dificuldade por favor reporte aqui de formas a mantermos a informação para todos.

**Comment by JoseCage** [comment]
@Zebedeu caso tenha alguma dúvida ou sugestão que queria discutir antes de passar para código pode mandar aqui.

**Comment by JoseCage** [comment]
Já tivemos um primeiro resultado..

Resolvido por |Complexidade | Pontos |
|--- |---| ---|
|@Zebedeu | Muito baixa | 10 |

Obrigado @Zebedeu pela disponibilidade..

Já tem 10 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by e200** [comment]
Permissão para fazer **push**.

**Comment by e200** [comment]
https://github.com/CDA-Exe/dojophp/tree/e200

**Comment by JoseCage** [comment]
> Permissão para fazer push.

Basta que faças o push e depois o **PullRequest** @e200 (que por acaso já o fizeste)..

Favor dar uma olhada no review que fiz no seu _PR_ #6

**Comment by guimar86** [comment]
<script src="https://gist.github.com/guimar86/1dd2c00e4c83f8bf4fbb4098685fa691.js"></script>

**Comment by guimar86** [comment]
Boas Cage, Este e o meu endereco gitHub. Renato Martins.
Aqui vai a minha resposta ao desafio inicial em php
https://gist.github.com/guimar86/1dd2c00e4c83f8bf4fbb4098685fa691

**Comment by JoseCage** [comment]
> Aqui vai a minha resposta ao desafio inicial em php
> https://gist.github.com/guimar86/1dd2c00e4c83f8bf4fbb4098685fa691

@guimar86 obrigado por submeter a sua resposta..

Entretanto só alguns pontos a corrigir:

* Os ficheiros devem ser trabalhados em seu ambiente de desenvolvimento e adicionados ao repositório via **Git** _não via Upload file_ do **Github**.
* Depois que resolver o exercício e fizer o push para seu repositório deve fazer o **pullrequest** para este que é o repo principal.
* De igual modo que fez a classe `MinhaCalculadora`, deve criar a classe de teste dentro da pasta `tests/`.
* Criar (se possivel) uma página html em que o seu código/classe possa ser implementado e executado

**PS**: Para já gostei da organização do código quanto ao retorno de erro.

**Comment by JoseCage** [comment]
Mais uma resposta submetida.

PullRequest da resposta #6  

Resolvido por |Complexidade | Tempo | Pontos |
|--- |---| ---| ---|
|@e200 | Muito baixa| 1 dia | 10 |

Obrigado @e200  pela disponibilidade..

Já tem 10 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by JoseCage** [comment]
Uma vez que já tivemos duas submissões ao exercício/desafio considero _desafio resolvido_..

Obrigado a todos por participarem..

**Comment by JoseCage** [comment]
Mais uma resposta submetida.

PullRequest da resposta #8 

Resolvido por |Complexidade | Tempo | Pontos |
|--- |---| ---| ---|
|@guimar | Muito baixa| indefinido (pull não mesclado ainda) | 10 |

Obrigado @guimar86   pela disponibilidade..

Já tem 10 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..
