### ISSUE TITLE
Consultar API do Github e retornar todos perfis de Luanda/Angola

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/dojophp#5]
Desafio| Complexidade| Pontos | Atribuido à |
|---| ---| ---| ---|
Consultar todos usuários github em Angola | Médio | 20 | #dojophp  |

Material de apoio:
 * [Github api-docs](https://developer.github.com/v3/users/) (**_users_**)
 * [Github api-docs](https://developer.github.com/v3/#timezones) (**_timezone_**)
* [Github search](https://developer.github.com/v3/search/#search-users) (_**users**_)
* [Search based on the location where a user resides](https://help.github.com/articles/searching-users/#search-based-on-the-location-where-a-user-resides) (_**search filters**_)

Usando a [API](https://developer.github.com/v3/) do Github (**v3**) retorne todos usuários que estejam localizados em Angola (_Luanda_ em particular)..
 Pode simplesmente retornar os dados em json ou se preferir pode ainda criar uma página html onde listará estes mesmos usuários.

**## Passos**
 * Faça o fork do repositório
 * Crie o seu branch onde irá trabalhar com o git
   Exemplo:  **`git checkout -b nome-da-branch`**
* Resolva o desafio e de seguida paça o push
  `git push --set-upstream nome-da-branch`

------------------
 **Nota**:  Mantenha o seu fork atualizado com as mudanças do repositório original
    
      git remote add upstream git@github.com:codingdojoangola/dojophp.git
      git checkout desafios
      git pull upstream desafios

**Comment by Orizon98** [comment]
Olá @JoseCage devo instalar o PHPUnit no meu projecto também?

**Comment by JoseCage** [comment]
Primeira resposta submetida.

PullRequest da resposta #11  

Resolvido por |Complexidade | Tempo | Pontos |
|--- |---| ---| ---|
| @e200  | Média | ***** | 10 |

Obrigado @e200    pela disponibilidade..

Já tem 10 pontos acumulado no nosso Dojo. Esperamos contar contigo em outros exercícios..

**Comment by JoseCage** [comment]
@e200 Falta apenas a página html para exibição dos resultados.
